PRIMERO: se crea un script para filtrado de datos de BD original
lauticouget/desercion_escolar_argentina pull request #8
Opened 2024-01-28 14:06 UTC by SooHav

Se creo un script .py para realizar el filtrado de datos solicitado, realiza las siguientes operaciones:
-une las dos bases de datos individual y hogar
-filtra por edad >= 14
-filtra por nivel educativo excluyendo (4 = Secundaria Completa, 5 = Superior Universitaria Incompleta, 6 = Superior Universitaria Completa, 7 = Sin instrucción,9 = Ns/Nr)
-se construyo una funcion que identifica los que cursan el trimestre incial y abandonan al siguiente.
-se ejecuta la funcion con un bucle for lo que retorna un dataframe concatenado con todos los trimestres.

2024-01-29 21:37 UTC, jbeiroa commented
Ojo @SooHav con la convención de nombres de las ramas y commits. Habíamos dicho que la rama tenía el mismo nombre que la tarea de trello y los commits iban como "nombre_rama: mensaje"

2024-01-30 13:46 UTC, jbeiroa requested changes
Según lo que hablamos hoy 30/1, habría que:
- Separar en asignación de variable objetivo y filtrado por edad y nivel educativo.
- Asegurar que devuelva lista de dataframes sin unirlos.

2024-01-30 13:46 UTC, jbeiroa commented on notebooks/filtrado.py
Habría que cambiar de lugar el archivo (la carpeta notebooks es sólo para notebooks).

2024-01-30 13:46 UTC, jbeiroa commented on notebooks/filtrado.py
> +    df_filtrado_edad_nivel['CODUSU_COMPONENTE'] = df_filtrado_edad_nivel['CODUSU'] + '_' + df_filtrado_edad_nivel['COMPONENTE'].astype(str)
Hay un problema con esto: el identificador de personas es [CODUSU, NRO_HOGAR, COMPONENTE].

2024-01-30 13:46 UTC, jbeiroa commented on notebooks/filtrado.py
> +        return df_resultado
Esto quizás deberían ser dos funciones, aunque empiezo a pensar que ese script únicamente debería agarrar la base de personas y ponerle la variable objetivo a cada una.

2024-01-30 13:46 UTC, jbeiroa commented on notebooks/filtrado.py
> +            df_individual_completo = pd.concat([df_individual_completo] + base_datos_tipo, ignore_index=True)
Acá es donde multiplicás datos: entre un trimestre y el siguiente siempre tenés un ~50% de repetidos, con lo cual al concatenar repetís valores. Más aún, entre un trimestre y el tercero que le sigue hay un ~25% de repetidos, con lo que hay varios hogares/personas que se repiten más de una vez.

Esto lo podés ver si agrupas por los identificadores y agregas contando valores. Por ej. para el de hogares:
`df_hogar_completo.groupby(['CODUSU', 'NRO_HOGAR']).size().reset_index(name='count')['count'].value_counts()`
--> 
1    27872
2    22681
4     5170
3     2007
Name: count, dtype: int64

2024-01-30 13:46 UTC, jbeiroa commented on notebooks/filtrado.py
> +            df_individual_completo = pd.concat([df_individual_completo] + base_datos_tipo, ignore_index=True)
De todos modos, me parece que arrancar uniendo todos los dataframes es para quilombo. Haría una función que tome un único df de personas (de un único trimestre) y aplique los filtros a ese df (total sobre el de hogares no hay condición alguna acá). Luego, con todo filtrado, se pone el target en cada trimestre y recien después se unen las bases de cada trimestre (tomando el recaudo de eliminar los duplicados antes de unir).

2024-01-30 23:49 UTC, SooHav reviewed
secreo una funcion que filtra la lista que contiene las bases de datos originales de individuos según las condiciones CH06 y NIVEL_ED. Devuelve otra lista de base de datos que contiene las siguientes columnas: CODUSU, ANO4, TRIMESTRE, NRO_HOGAR, COMPONENTE,CH06, CH10, NIVEL_ED.

2024-01-30 23:51 UTC, SooHav reviewed
Se creo una función  que obtiene una lista de bases de datos originales para un tipo específico ("hogar" o "individual"), años y periodos dados.

2024-01-31 13:54 UTC, SooHav reviewed
Esta funcion genera una lista de bases de datos con las columnas requeridas y el target de deserción adjunto, para los pares de periodos a estudiar.

2024-01-31 13:56 UTC, SooHav reviewed
Se modificó en el docstring el ejemplo de lista de periodos requeridos para correr la función.

2024-01-31 14:45 UTC, SooHav reviewed
Se creó una función que elimina los individuos duplicados entre las bases de datos de la lista. Copia la lista original para no modificarla y devuelve otra lista de BD sin individuos duplicados.

2024-01-31 14:47 UTC, jbeiroa commented
Esto va en general para todos los archivos: para mí tiene que haber una función que actúe sobre un único período, y luego loopear esa función sobre la lista de bases. Sino, las funciones sólo funcionan sobre una lista de períodos y no sirven si queremos usarlas sobre una sola (o habría que pasarla en una lista de un único elemento, cosa que no tiene sentido).

2024-01-31 15:33 UTC, SooHav commented
Decis que en vez de recibir una lista para que opere con ella solo reciba
una única BD y luego hacer los bucles por fuera.
En principio no me pareció un problema ya que trabajaremos con las listas
de base de datos para tener una lista de bases de datos final procesada y
filtrada. La ventaja es que nos deja más limpio el script principal. En
todo caso hago todas las funciones de nuevo para que trabajen con bases de
datos individuales, no borro las que están hechas y luego se decide cuales
dejar en función de la longitud y complejidad del script principal.

El mié, 31 ene 2024 a la(s) 11:48 a.m., Juan Ignacio Beiroa (
***@***.***) escribió:

> Esto va en general para todos los archivos: para mí tiene que haber una
> función que actúe sobre un único período, y luego loopear esa función sobre
> la lista de bases. Sino, las funciones sólo funcionan sobre una lista de
> períodos y no sirven si queremos usarlas sobre una sola (o habría que
> pasarla en una lista de un único elemento, cosa que no tiene sentido).
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lauticouget/desercion_escolar_argentina/pull/8#issuecomment-1919255011>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BC2624TCPNUPFS6CV2PE5KLYRJKSDAVCNFSM6AAAAABCOGO2IGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMJZGI2TKMBRGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-01-31 16:02 UTC, SooHav reviewed
Funcion que filtra una de base de datos según las condiciones especificadas: CH06 y NIVEL_ED.

2024-01-31 16:33 UTC, SooHav reviewed
Función que genera la columna target en dos bases de datos filtradas seleccionadas temporalmente: periodo  inicial y periodo final, con los siguientes valores: no asiste (2), no desertó (1), deserto (0) en cada base de datos. La msima podría ser utilizada para periodos consecutivos, con diferencia anual o lo indicado.

2024-01-31 17:12 UTC, SooHav reviewed
Funcion que obtiene una base de datos para un tipo específico, año y periodo dado.

2024-02-01 22:13 UTC, jbeiroa approved these changes
@SooHav mergealo a develop, y mañana hacemos una rama para hacer el construir_dataset.py y vamos viendo qué modificaciones le hacemos a todos estos archivos y los que fui subiendo yo para que todo ande dentro del construir_dataset.py.

2024-02-01 22:13 UTC, jbeiroa commented on desercion_escolar_argentina/utils/seleccion_de_features.py
Este archivo no es el que se debería eliminar.

2024-02-01 22:13 UTC, jbeiroa commented on desercion_escolar_argentina/utils/variable_objetivo.py
> +def variable_objetivo(lista: list, periodos_requeridos: list, columnas_requeridas:list) -> list:
Acá, por ejemplo: la función tiene que funcionar sobre un único período, y luego loopeamos esa función en la lista de bases.

2024-02-01 22:13 UTC, jbeiroa commented on desercion_escolar_argentina/utils/variable_objetivo.py
> +    con los siguientes valores no asiste: 2, no desertó: 1, deserto:0 en cada base de datos.
Pero la variable target tiene que ser binaria!

2024-02-01 22:13 UTC, jbeiroa commented on desercion_escolar_argentina/utils/variable_objetivo.py
> +    con los siguientes valores no asiste: 2, no desertó: 1, deserto:0 en cada base de datos.
Hay un error de lógica con la asignación de la variable objetivo.

_Partiendo de tener una función que actúe sobre un único dataframe:_
La función tendría que tomar una dataframe que contenga ['CODUSU', 'NRO_HOGAR', 'COMPONENTE', 'CH10_t', 'CH10_t+1'] donde 'CH10_t' es la condición de asistencia de un trimestre y 'CH10_t+1' es la condición de asistencia en el trimestre sigueinte. Para mí el dataframe debería venir mergeado de antes con esas variables, o a lo sumo hacerse dentro de la función pero con no más de dos dataframes.
Ahí hay que filtrar y quedarse sólo con los CH10_t == 1 y luego asignar la variable objetivo según CH10t+1: si es 2, desertó al trimestre siguiente, darle valor 1 al target (que evalúa a TRUE) y si es 1 darle valor 0 al target (que evalúa a FALSE). _Luego la función devuelve un único df con _['CODUSU', 'NRO_HOGAR', 'COMPONENTE', 'target']_

Si luego tenemos una lista de dataframes, lo que se hace es loopear la función que actúa sobre uno sólo o de a pares sobre la lista.

2024-02-01 22:13 UTC, jbeiroa commented on desercion_escolar_argentina/utils/filtrar_datos.py
> +def filtrar_edad_nivel_ed(lista_base_datos: list)->list:
Acá lo mismo: la función tendría que actuar sobre un único dataframe, y después se loopea esa función sobre la lista.

2024-02-01 22:13 UTC, jbeiroa commented on desercion_escolar_argentina/utils/filtro_duplicados.py
Tiene que haber una forma menos nesteada de hacer esto. 
Algo como:
`db1[['CODUSU', 'NRO_HOGAR', 'COMPONENTE']].isin(db2[['CODUSU', 'NRO_HOGAR', 'COMPONENTE']])`
debería dar una máscara booleana de cuáles ['CODUSU', 'NRO_HOGAR', 'COMPONENTE'] de db1 están dentro de db2 y cuáles no con los cuales slicear y sacar los duplicados.

2024-02-01 22:13 UTC, jbeiroa commented on desercion_escolar_argentina/utils/filtrar_datos.py
> +        lista_bd_filtrada.append(bd_filtrada)
Acá uno pondría la función de filtro_datos.py dentro del for. O directamente se usa en una list comprehension.

2024-02-01 22:13 UTC, jbeiroa commented on desercion_escolar_argentina/utils/scraper.py
> +                print(f"Error obteniendo base de datos para {tipo}, año {anio}, periodo: {e}")
Lo mismo. Acá adentro se usaría la descargar_datos.

2024-02-02 13:37 UTC, merged